# Generated by Django 5.2.6 on 2025-09-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=5000)),
                ('category', models.CharField(choices=[('network_security', 'Network Security'), ('web_app_security', 'Web Application Security'), ('cloud_security', 'Cloud Security'), ('cryptography', 'Cryptography'), ('digital_forensics', 'Digital Forensics'), ('malware_analysis', 'Malware Analysis'), ('penetration_testing', 'Penetration Testing'), ('reverse_engineering', 'Reverse Engineering'), ('incident_response', 'Incident Response'), ('threat_intelligence', 'Threat Intelligence'), ('compliance_governance', 'Security Compliance & Governance'), ('secure_coding', 'Secure Coding Practices'), ('identity_access', 'Identity & Access Management'), ('security_awareness', 'Security Awareness & Training'), ('red_team', 'Red Teaming'), ('blue_team', 'Blue Teaming'), ('purple_team', 'Purple Teaming'), ('iot_security', 'IoT Security'), ('mobile_security', 'Mobile Security'), ('os_security', 'Operating System Security')])),
                ('link', models.URLField(help_text='Enter the full URL (e.g., https://example.com)', unique=True)),
            ],
        ),
    ]
