# Generated by Django 5.2.6 on 2025-09-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceManager', '0002_alter_resource_description_alter_resource_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
